clear all;
clc;
global global_info;
global_info.STOP_AT = 5000;
global_info.Quality = {'AQuality','BQuality'};

pns = pnstruct('football_pn_pdf');
dynamic.m0 = {'pProduction',5};
dynamic.ft = {
    'allothers',5};
dynamic.re = {'rMaterialCutting',10,480,...
    'rLamination',20,8,...
    'rPanelCutting',50,8,...
    'rPritting',200,8,...
    'rSorttingMatching',20,8,...
    'rBladerWeight',20,8,...
    'rStiching',1000,inf,...
    'rQualityAsurance',10,8,...
    'rWashing',10,8,...
    'rPacking',50,8};
pni = initialdynamics(pns, dynamic);
sim = gpensim(pni);
plotp(sim, {
    'pProduction',...
    'pMatterialCutting',...
    'pLamination',...
    'pPanelCutting',...
    'pPrinting',...
    'pSorttingMatching',...
    'pBladerWeight',...
    'pStiching',...
    'pQualityAsurance',...
    'pWashing',...
    'pPacking',...
    'pPacked',...
    'pDispose'
    });
prnschedule(sim);
plotGC(sim);
prnss(sim);
%prnfinalcolors(sim);
% prncolormap(sim);