function [png] = football_pn_pdf()
png.PN_name = 'Football petrinet definition';
png.set_of_Ps = {'pRawMaterialStore',...
    'pProduction',...
    'pMatterialCutting',...
    'pLamination',...
    'pPanelCutting',...
    'pPritting',...
    'pSorttingMatching',...
    'pBladerWeight',...
    'pStiching',...
    'pQualityAsurance',...
    'pWashing',...
    'pPacking',...
    'pPacked'};
png.set_of_Ts = {'tTransferMatterialCutting',...
    'tMatterialCutting',...
    'tLamination',...
    'tPanelCutting',...
    'tPritting',...
    'tSorttingMatching',...
    'tBladerWeight',...
    'tStiching',...
    'tQualityAsurance',...
    'tWashing',...
    'tPacking',...
    'tPacked'};
png.set_of_As = {'pRawMaterialStore','tTransferMatterialCutting',1,...
    'pProduction','tTransferMatterialCutting',1,...
    'tTransferMatterialCutting','pMatterialCutting',1,...
    'pMatterialCutting','tMatterialCutting',1,...
    'tMatterialCutting','pLamination',1,...
    'pLamination','tLamination',1,...
    'tLamination','pPanelCutting',1,...
    'pPanelCutting','tPanelCutting',1,...
    'tPanelCutting','pPritting',1,...
    'pPritting','tPritting',1,...
    'tPritting','pSorttingMatching',1,...
    'pSorttingMatching','tSorttingMatching',1,...
    'tSorttingMatching','pBladerWeight',1,...
    'pBladerWeight','tBladerWeight',1,...
    'tBladerWeight','pStiching',1,...
    'pStiching','tStiching',1,...
    'tStiching','pQualityAsurance',1,...
    'pQualityAsurance','tQualityAsurance',1,...
    'tQualityAsurance','pWashing',1,...
    'pWashing','tWashing',1,...
    'tWashing','pPacking',1,...
    'pPacking','tPacking',1,...
    'tPacking','pPacked',1,...
    'pPacked','tPacked',1,...
    'tPacked' , 'pProduction', 1    
    }; 