clear all;
clc;
global global_info;
% Simulation time considered as one working day
global_info.STOP_AT = 120;

% Quality colors used in simulations, to differentiate Quality of Ball
global_info.Quality = {'AQuality','BQuality'};

pns = pnstruct('football_pn_pdf');
dynamic.m0 = {'pProduction',20};
% Firing time of each transition, normalised based on the actual time data
% provided by the company.
dynamic.ft = {
    'tTransferMaterialCutting',0.1,...
    'tQualityAsurance',0.1,...
    'tQualityTested',0.1,...
    'tTransferDispose',0.1,...
    'tTransferAQ',0.1,...
    'tWashing',1,...
    'allothers',4};
% firing costs of each transition based on the cost data provided 
% by the company.
dynamic.fc_fixed = {
    'tMaterialCutting',175,...
    'tLamination',729,...
    'tPanelCutting',438,...
    'tPrinting',1458,...
    'tSorttingMatching',175,...
    'tBladerWeight',175,...
    'tStiching',146,...
    'tQualityAsurance',59,...
    'tWashing',59,...
    'tPacking',525};
dynamic.fc_variable = {'tMaterialCutting',2,...
    'tLamination',5,...
    'tPanelCutting',12,...
    'tPrinting',14,...
    'tSorttingMatching',1,...
    'tBladerWeight',3,...
    'tStiching',1,...
    'tQualityAsurance',16,...
    'tWashing',17,...
    'tPacking',18};

% number of human resources (employees) in eacch department
% we set the lifecycle of resource as inf, because we are running for one
% day so as along as the simulation is running it should be able to utilize
% employees
dynamic.re = {
    'rMaterialCutting',24,16,...
    'rLamination',125,4,...
    'rPanelCutting',75,8,...
    'rPrinting',250,4,...
    'rSorttingMatching',30,20,...
    'rBladerWeight',30,20,...
    'rStiching',25,inf,...
    'rQualityAsurance',10,40,...
    'rWashing',10,40,...
    'rPacking',90,4
    };

% dynamic.rc_fixed={'rMaterialCutting',14000};
% dynamic.rc_variable={'rMaterialCutting',14000};

pni = initialdynamics(pns, dynamic);
sim = gpensim(pni);
plotp(sim, {
    'pProduction',...
    'pMatterialCutting',...
    'pLamination',...
    'pPanelCutting',...
    'pPrinting',...
    'pSorttingMatching',...
    'pBladerWeight',...
    'pStiching',...
    'pQualityAsurance',...
    'pWashing',...
    'pPacking',...
    'pPacked',...
    'pDispose'
    });
% prnschedule(sim);
 plotGC(sim);
% prnss(sim);
prnfinalcolors(sim,{'pPacked'
    });
prnschedule(sim);