function [png] = football_pn_pdf()
png.PN_name = 'Football petrinet definition';
png.set_of_Ps = {
    'pProduction',...
    'pMatterialCutting',...
    'pLamination',...
    'pPanelCutting',...
    'pPritting',...
    'pSorttingMatching',...
    'pBladerWeight',...
    'pStiching',...
    'pQualityAsurance',...
    'pWashing',...
    'pPacking',...
    'pPacked'
    };
png.set_of_Ts = {'tTransferMaterialCutting',...
    'tMaterialCutting',...
    'tLamination',...
    'tPanelCutting',...
    'tPritting',...
    'tSorttingMatching',...
    'tBladerWeight',...
    'tStiching',...
    'tQualityAsurance',...
    'tWashing',...
    'tPacking'
};
png.set_of_As = {
    'pProduction','tTransferMaterialCutting',1,...
    'tTransferMaterialCutting','pMatterialCutting',1,...
    'pMatterialCutting','tMaterialCutting',1,...
    'tMaterialCutting','pLamination',100,...
    'pLamination','tLamination',100,...
    'tLamination','pPanelCutting',100,...
    'pPanelCutting','tPanelCutting',100,...
    'tPanelCutting','pPritting',100,...
    'pPritting','tPritting',100,...
    'tPritting','pSorttingMatching',100,...
    'pSorttingMatching','tSorttingMatching',100,...
    'tSorttingMatching','pBladerWeight',100,...
    'pBladerWeight','tBladerWeight',100,...
    'tBladerWeight','pStiching',100,...
    'pStiching','tStiching',100,...
    'tStiching','pQualityAsurance',100,...
    'pQualityAsurance','tQualityAsurance',100,...
    'tQualityAsurance','pWashing',100,...
    'pWashing','tWashing',100,...
    'tWashing','pPacking',100,...
    'pPacking','tPacking',100,...
    'tPacking','pPacked',100
    }; 