clear all;
clc;
global global_info;
global_info.STOP_AT = 100;
global_info.Quality = {'AQuality','BQuality'};

pns = pnstruct('football_pn_pdf');
dynamic.m0 = {'pProduction',20};
dynamic.ft = {
    'tLamination',2.7,...
    'tPrintingCutting',3,...
    'tQualityAsurance',0.04,...
    'tQualityTested',0.04,...
    'tTransferDispose',0.04,...
    'tTransferAQ',0.04,...
    'allothers',4};
%firing costs.
dynamic.fc_fixed = {
    'tLamination',52,...
    'tPrintingCutting',52,...
    'tSorttingMatching',175,...
    'tBladerWeight',175,...
    'tStiching',146,...
    'tQualityAsurance',59,...
    'tWashing',59,...
    'tPacking',525};
% production overheads as variable cost
dynamic.fc_variable = {
    'tLamination',5,...
    'tPrintingCutting',12,...
    'tSorttingMatching',1,...
    'tBladerWeight',3,...
    'tStiching',1,...
    'tQualityAsurance',16,...
    'tWashing',17,...
    'tPacking',18};
%number of human and machine resources in eacch department
dynamic.re = {
    'rLaminationHuman',9,16,...    
    'rLaminationMachine',3,16,...
    'rPrintingCuttingHuman',9,16,...
    'rPrintingCuttingMachine',3,16,...
    'rSorttingMatching',30,20,...
    'rBladerWeight',30,20,...
    'rStiching',25,inf,...
    'rQualityAsurance',10,40,...
    'rWashing',10,40,...
    'rPacking',90,4
    };
% price and costs of machines 
 dynamic.rc_fixed={'rLaminationMachine',1000,'rPrintingCuttingMachine',1200};
 dynamic.rc_variable={'rLaminationMachine',10,'rPrintingCuttingMachine',12};

pni = initialdynamics(pns, dynamic);
sim = gpensim(pni);
plotp(sim, {
    'pProduction',...
    'pLamination',...
    'pPrintingCutting',...
    'pSorttingMatching',...
    'pBladerWeight',...
    'pStiching',...
    'pQualityAsurance',...
    'pWashing',...
    'pPacking',...
    'pPacked',...
    'pDispose'
    });
 prnschedule(sim);
 plotGC(sim);
 prnss(sim);
 prnfinalcolors(sim);
 prnschedule(sim);
%  cotree(pni,1,1);