clear all;
clc;
global global_info;
global_info.STOP_AT = 800;
global_info.Quality = {'AQuality','BQuality'};

pns = pnstruct('football_pn_pdf');
dynamic.m0 = {'pProduction',20};
dynamic.ft = {
    'tLamination',2,...
    'tPrintingCutting',4,...
    'tSorttingMatching',4,...
    'tBladerWeight',4,...
    'tStiching',4,...
    'tQualityAsurance',1,...
    'tQualityTester',1,...
    'tQualityTested',1,...
    'tTransferDispose',1,...
    'tTransferAQ',1,...
    'tWashing',4,...
    'tPacking',4,...
    'allothers',1};
%firing costs.
dynamic.fc_fixed = {'tQualityTester',50, 'tTransferAQ',100};
dynamic.fc_variable = {'tQualityTester',20, 'tTransferAQ',25};
%number of human resources in eacch department
dynamic.re = {
    'rLaminationHuman',6,inf,...    
    'rLaminationMachine',2,inf,...
    'rPrintingCuttingHuman',6,inf,...
    'rPrintingCuttingMachine',2,inf,...
    'rSorttingMatching',30,inf,...
    'rBladerWeight',30,inf,...
    'rStiching',25,inf,...
    'rQualityAsurance',10,inf,...
    'rWashing',10,8,...
    'rPacking',90,inf
    };

% dynamic.rc_fixed={'rMaterialCutting',14000};
% dynamic.rc_variable={'rMaterialCutting',14000};

pni = initialdynamics(pns, dynamic);
sim = gpensim(pni);
plotp(sim, {
    'pProduction',...
    'pLamination',...
    'pPrintingCutting',...
    'pSorttingMatching',...
    'pBladerWeight',...
    'pStiching',...
    'pQualityAsurance',...
    'pWashing',...
    'pPacking',...
    'pPacked',...
    'pDispose'
    });
% prnschedule(sim);
 plotGC(sim);
% prnss(sim);
prnfinalcolors(sim);
prnschedule(sim);